[package]
name = "consumer"
version = "0.1.0"
edition = "2021"


[dependencies]
chrono = "0.4.31"
env_logger = "0.10.1"
log = "0.4.20"
rdkafka = { version = "^0.29", features = ["cmake-build"] }
tokio = { version = "1", features = ["full"] }
